services:
  web:
    build: .
    command: gunicorn MiProyecto.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST: db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/usr/share/nginx/html/staticfiles  # Mapea el volumen en Nginx
      - ./media:/usr/share/nginx/html/media  # Mapea el volumen en Nginx
    depends_on:
      - web

  test:
    build: .
    command: pytest  # Ejecuta pytest al iniciar este contenedor
    volumes:
      - .:/app
    depends_on:
      - db
    entrypoint: ["tail", "-f", "/dev/null"]  # Evita que se ejecute automáticamente

volumes:
  postgres_data:

